# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyagent < Formula
  desc "Lazygit-style TUI for skills, subagents, MCP servers, prompts and memory across Claude Code, Codex and Gemini CLI."
  homepage "https://github.com/mi-subbotin/lazyagent"
  version "0.4.8"
  license "Apache-2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/mi-subbotin/lazyagent/releases/download/v0.4.8/lazyagent_0.4.8_darwin_amd64.tar.gz"
    sha256 "d9c73ebbaf953c434707d12a502baff638c42738f425126648c80ae7bdef7d16"

    define_method(:install) do
      bin.install "lazyagent"
      bash_completion.install "completions/lazyagent.bash" => "lazyagent"
      zsh_completion.install "completions/lazyagent.zsh" => "_lazyagent"
      fish_completion.install "completions/lazyagent.fish" => "lazyagent.fish"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/mi-subbotin/lazyagent/releases/download/v0.4.8/lazyagent_0.4.8_darwin_arm64.tar.gz"
    sha256 "47bb56d13c71a32dbfebc84c304dc401443aeb6f0f353bf32db41eb57541c563"

    define_method(:install) do
      bin.install "lazyagent"
      bash_completion.install "completions/lazyagent.bash" => "lazyagent"
      zsh_completion.install "completions/lazyagent.zsh" => "_lazyagent"
      fish_completion.install "completions/lazyagent.fish" => "lazyagent.fish"
    end
  end

  def caveats
    <<~EOS
      First launch on macOS triggers Gatekeeper because the binary
      isn't notarized. If that hits you:
        xattr -d com.apple.quarantine "$(which lazyagent)"
      Notarization is on the roadmap for a later release.
    EOS
  end

  test do
    assert_match "lazyagent", shell_output("#{bin}/lazyagent --version")
  end
end
