# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyagent < Formula
  desc "Lazygit-style TUI for skills, subagents, MCP servers, prompts and memory across Claude Code, Codex and Gemini CLI."
  homepage "https://github.com/mi-subbotin/lazyagent"
  version "0.4.0"
  license "Apache-2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/mi-subbotin/lazyagent/releases/download/v0.4.0/lazyagent_0.4.0_darwin_amd64.tar.gz"
    sha256 "7b476523d5a66fce247732087b5ca997a87cc65e3f7dc127eca0027698a3c6cf"

    define_method(:install) do
      bin.install "lazyagent"
      bash_completion.install "completions/lazyagent.bash" => "lazyagent"
      zsh_completion.install "completions/lazyagent.zsh" => "_lazyagent"
      fish_completion.install "completions/lazyagent.fish" => "lazyagent.fish"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/mi-subbotin/lazyagent/releases/download/v0.4.0/lazyagent_0.4.0_darwin_arm64.tar.gz"
    sha256 "da9408656d7cfb9d54ddba55b92085909a23d8e2aea922dc9d30c00c9e179e50"

    define_method(:install) do
      bin.install "lazyagent"
      bash_completion.install "completions/lazyagent.bash" => "lazyagent"
      zsh_completion.install "completions/lazyagent.zsh" => "_lazyagent"
      fish_completion.install "completions/lazyagent.fish" => "lazyagent.fish"
    end
  end

  def caveats
    <<~EOS
      First launch on macOS triggers Gatekeeper because the binary
      isn't notarized. If that hits you:
        xattr -d com.apple.quarantine "$(which lazyagent)"
      Notarization is on the roadmap for a later release.
    EOS
  end

  test do
    assert_match "lazyagent", shell_output("#{bin}/lazyagent --version")
  end
end
