# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyagent < Formula
  desc "Lazygit-style TUI for skills, subagents, MCP servers, prompts and memory across Claude Code, Codex and Gemini CLI."
  homepage "https://github.com/mi-subbotin/lazyagent"
  version "0.5.0"
  license "Apache-2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/mi-subbotin/lazyagent/releases/download/v0.5.0/lazyagent_0.5.0_darwin_amd64.tar.gz"
    sha256 "e89c6b0603e547e2ae91cfab0e89964de479ef8b657f04459b8272bb3ee5800b"

    define_method(:install) do
      bin.install "lazyagent"
      bash_completion.install "completions/lazyagent.bash" => "lazyagent"
      zsh_completion.install "completions/lazyagent.zsh" => "_lazyagent"
      fish_completion.install "completions/lazyagent.fish" => "lazyagent.fish"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/mi-subbotin/lazyagent/releases/download/v0.5.0/lazyagent_0.5.0_darwin_arm64.tar.gz"
    sha256 "a77b73bbee891f8d6fa73d910e4adf555fc72ed3645c5c6cd373ea83ab8ba1ba"

    define_method(:install) do
      bin.install "lazyagent"
      bash_completion.install "completions/lazyagent.bash" => "lazyagent"
      zsh_completion.install "completions/lazyagent.zsh" => "_lazyagent"
      fish_completion.install "completions/lazyagent.fish" => "lazyagent.fish"
    end
  end

  def caveats
    <<~EOS
      First launch on macOS triggers Gatekeeper because the binary
      isn't notarized. If that hits you:
        xattr -d com.apple.quarantine "$(which lazyagent)"
      Notarization is on the roadmap for a later release.
    EOS
  end

  test do
    assert_match "lazyagent", shell_output("#{bin}/lazyagent --version")
  end
end
